openapi: 3.0.0
servers:
  - url: 'http://127.0.0.1:8080'
info:
  description: >-
    Retrieve comments made by users on a podcast
  version: 1.0.0
  title: Podcast Comments
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: comment
    description: Everything about comments

paths:
  /comment:
    post: 
      tags:
        - comment
      summary: Add a new comment to the podcast
      description: ''
      operationId: addComment
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Comment'
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '405':
          description: Invalid input
      security:
        - podcast_auth:
            - 'write:comments'
            - 'read:comments'

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'

    get:
      tags:
        - comment
      summary: Get all comments
      description: ''
      operationId: getComment
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Comment'

components:
  requestBodies:
    Comment:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Comment'
        application/xml:
          schema:
            $ref: '#/components/schemas/Comment'
      description: Comment object that needs to be added to the podcast
      required: true
  schemas:
    Comment:
      title: a Comment
      description: A pet for sale in the pet store
      type: object
      properties:
        id:
          type: integer
          format: int64
        body:
          type: string
          description: comment's body
      xml:
        name: Comment